# Generated by Django 5.2.6 on 2025-09-21 16:06

import apps.utils
import functools
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='image',
            field=models.ImageField(upload_to=functools.partial(apps.utils.file_upload_path, *('course',), **{'directory': 'courses'}), verbose_name='course image'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='students',
            field=models.ManyToManyField(related_name='student_courses', through='course.CourseStudentsThrough', to=settings.AUTH_USER_MODEL, verbose_name='students'),
        ),
    ]
